#!/usr/bin/env node
/**
 * Generates sitemap.xml from the real pages in this folder.
 *
 * A page is included only if it is all of:
 *   - a real .html file at the repo root
 *   - not on the EXCLUDE list (error pages, unserved reserves)
 *   - not carrying <meta name="robots" content="noindex">
 *   - carrying a <link rel="canonical"> (which supplies the URL, so the
 *     sitemap and the canonical tag can never disagree)
 *
 * That last rule is deliberate: the sitemap is derived from the canonicals
 * rather than maintained by hand, so a page that gets noindexed or has its
 * canonical changed drops out or moves on its own.
 *
 * Usage:
 *   node scripts/generate-sitemap.mjs           # write sitemap.xml
 *   node scripts/generate-sitemap.mjs --check   # verify it is up to date (CI)
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// Pages that must never appear in a sitemap regardless of their tags.
const EXCLUDE = new Set([
  '404.html',   // error page
]);
// The coming-soon holding page at index.html excludes itself via its own
// noindex tag, so it needs no entry here.

const pages = readdirSync(ROOT)
  .filter((f) => f.endsWith('.html'))
  .filter((f) => !EXCLUDE.has(f))
  .sort();

const entries = [];
const skipped = [];

for (const file of pages) {
  const html = readFileSync(join(ROOT, file), 'utf8');

  // Strip comments first so prose mentioning "noindex" or a canonical inside
  // an explanatory comment cannot be mistaken for a real tag.
  const live = html.replace(/<!--[\s\S]*?-->/g, '');

  if (/<meta\s+name=["']robots["'][^>]*content=["'][^"']*noindex/i.test(live)) {
    skipped.push({ file, why: 'noindex' });
    continue;
  }

  const canonical = live.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["']/i);
  if (!canonical) {
    skipped.push({ file, why: 'no canonical tag' });
    continue;
  }

  const lastmod = statSync(join(ROOT, file)).mtime.toISOString().slice(0, 10);
  entries.push({ file, loc: canonical[1], lastmod });
}

entries.sort((a, b) => a.loc.length - b.loc.length || a.loc.localeCompare(b.loc));

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  entries
    .map((e) => `  <url>\n    <loc>${e.loc}</loc>\n    <lastmod>${e.lastmod}</lastmod>\n  </url>\n`)
    .join('') +
  `</urlset>\n`;

const target = join(ROOT, 'sitemap.xml');

if (CHECK) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  // Compare only the <loc> set, so a lastmod drift from touching a file does
  // not fail CI — the URLs are what matter.
  const locsOf = (s) => (s.match(/<loc>([^<]+)<\/loc>/g) || []).sort().join('|');
  if (locsOf(current) !== locsOf(xml)) {
    console.error('FAIL  sitemap.xml is out of date.');
    console.error('      Expected URLs:');
    entries.forEach((e) => console.error(`        ${e.loc}   (${e.file})`));
    console.error('      Run: node scripts/generate-sitemap.mjs');
    process.exit(1);
  }
  console.log(`PASS  sitemap.xml is up to date (${entries.length} URLs).`);
} else {
  writeFileSync(target, xml);
  console.log(`Wrote sitemap.xml with ${entries.length} URLs:`);
  entries.forEach((e) => console.log(`  ${e.loc}   (${e.file})`));
}

if (skipped.length) {
  console.log('\nExcluded from sitemap:');
  skipped.forEach((s) => console.log(`  ${s.file}  — ${s.why}`));
}
